import { parseProject, type Project } from "@loom/spec";

/**
 * A self-contained 3-scene fixture used to prove the renderer before any AI is
 * wired in. Assets live in packages/render/public/ and are generated by
 * scripts/make-fixtures.ts (solid/gradient PNGs + sine-tone audio) so the whole
 * thing renders offline with no downloads.
 *
 * Parsed through parseProject so it can never drift from the schema: if the spec
 * changes incompatibly, importing this module throws.
 */
export const fixtureProject: Project = parseProject({
  id: "fixture-explainer",
  meta: {
    title: "Loom — fixture explainer",
    aspectRatio: "16:9",
    fps: 30,
    resolution: [1920, 1080],
  },
  style: {
    palette: { bg: "#0b1020", fg: "#f5f7ff", accent: "#7c6cff" },
    fonts: { display: "Inter", body: "Inter" },
  },
  // Background music that ducks under narration: it plays at `volume` in the
  // gaps and dips to `duckTo` whenever a scene's audio is speaking.
  music: { track: "assets/music/bg.mp3", volume: 0.3, duckTo: 0.06 },
  scenes: [
    {
      id: "s1",
      script: "Loom turns a prompt into a finished explainer video.",
      audio: { path: "assets/audio/s1.mp3", durationMs: 3000 },
      transition: { type: "fade", durationMs: 250 },
      slides: [
        {
          id: "s1-title",
          layout: "title",
          startMs: 0,
          durationMs: 3000,
          content: { title: "Loom", subtitle: "Talk to Claude. Get an MP4." },
        },
      ],
    },
    {
      id: "s2",
      script: "Every video is a typed JSON spec that AI generates and mutates.",
      audio: { path: "assets/audio/s2.mp3", durationMs: 3000 },
      transition: { type: "fade", durationMs: 250 },
      slides: [
        {
          id: "s2-image",
          layout: "image",
          startMs: 0,
          durationMs: 3000,
          content: { src: "assets/images/grad.png", alt: "gradient", fit: "cover" },
          // Slow zoom-in to prove Ken Burns motion is honoured.
          motion: {
            type: "kenBurns",
            from: { x: 0, y: 0, width: 1, height: 1 },
            to: { x: 0.08, y: 0.06, width: 0.84, height: 0.84 },
          },
        },
      ],
    },
    {
      id: "s3",
      script: "Remotion renders the spec. Claude Code is the editing UI.",
      audio: { path: "assets/audio/s3.mp3", durationMs: 3000 },
      transition: { type: "fade", durationMs: 250 },
      slides: [
        {
          id: "s3-imagetext",
          layout: "imageText",
          startMs: 0,
          durationMs: 3000,
          content: {
            src: "assets/images/grid.png",
            heading: "Pure spec in, MP4 out",
            body: "No timeline. No proprietary container. Just project.json.",
            position: "bottom",
            fit: "cover",
          },
        },
      ],
    },
    {
      // No audio: a chart can stand on its own. Proves the `chart` layout renders
      // (grouped bars with a value axis + legend) straight from spec data.
      id: "s4",
      script: "Charts bake straight into the spec — data in, animated chart out.",
      transition: { type: "fade", durationMs: 250 },
      slides: [
        {
          id: "s4-chart",
          layout: "chart",
          startMs: 0,
          durationMs: 4000,
          content: {
            chartType: "bar",
            title: "Renders per stage",
            xKey: "stage",
            yKeys: ["draft", "final"],
            data: [
              { stage: "plan", draft: 8, final: 2 },
              { stage: "script", draft: 6, final: 3 },
              { stage: "voice", draft: 4, final: 4 },
              { stage: "slides", draft: 9, final: 5 },
            ],
          },
        },
      ],
    },
    {
      // No audio: proves the `bullets` layout renders (title + cascading items).
      id: "s5",
      script: "Each pipeline stage is a pure spec mutation you can re-roll on its own.",
      transition: { type: "fade", durationMs: 250 },
      slides: [
        {
          id: "s5-bullets",
          layout: "bullets",
          startMs: 0,
          durationMs: 4000,
          content: {
            title: "Every stage is a pure spec mutation",
            items: [
              "plan turns a prompt into scenes",
              "script polishes narration and beats",
              "voice and align add audio + captions",
              "slides fills in the imagery",
              "render is a pure function of the spec",
            ],
          },
        },
      ],
    },
    {
      // No audio: proves the `quote` layout renders (accent mark + attribution).
      id: "s6",
      script: "The spec is the durable artifact — every frame derives from it.",
      transition: { type: "fade", durationMs: 250 },
      slides: [
        {
          id: "s6-quote",
          layout: "quote",
          startMs: 0,
          durationMs: 3500,
          content: {
            text: "The video is a typed JSON spec. Everything else is derived.",
            attribution: "Loom",
          },
        },
      ],
    },
    {
      // No audio: proves the `code` layout renders syntax-highlighted source,
      // cascades the lines in, and emphasizes the `highlight` lines.
      id: "s7",
      script: "A slide can be a code block — highlighted, with the key lines called out.",
      transition: { type: "fade", durationMs: 250 },
      slides: [
        {
          id: "s7-code",
          layout: "code",
          startMs: 0,
          durationMs: 4000,
          content: {
            language: "ts",
            title: "render.ts",
            // Emphasize the return so the eye lands on "the spec is the input".
            highlight: [4],
            code: [
              "export function render(spec: Project) {",
              '  const timeline = layoutTimeline(spec);',
              "  // every frame is derived from the spec",
              "  return renderFrames(timeline);",
              "}",
            ].join("\n"),
          },
        },
      ],
    },
    {
      // No audio: proves the `code` layout's diff mode tints +/- rows.
      id: "s8",
      script: "In diff mode the same layout tints additions green and removals red.",
      transition: { type: "fade", durationMs: 250 },
      slides: [
        {
          id: "s8-diff",
          layout: "code",
          startMs: 0,
          durationMs: 3500,
          content: {
            language: "diff",
            title: "slide.ts",
            code: [
              "@@ IMPLEMENTED_LAYOUTS @@",
              '-  \"chart\", \"bullets\", \"quote\",',
              '+  \"chart\", \"bullets\", \"quote\", \"code\",',
              " ] as const;",
            ].join("\n"),
          },
        },
      ],
    },
    {
      // No audio: a `manim` slide as a *brief* (sceneName + sceneSource, no clip
      // yet). It renders the "Manim pending" placeholder so the fixture stays
      // watchable offline without a Manim install; `loom manim` would fill in the
      // clip. Proves the layout is wired end-to-end through the schema + renderer.
      id: "s9",
      script: "Technical scenes can be real Manim animations, rendered and embedded.",
      transition: { type: "fade", durationMs: 250 },
      slides: [
        {
          id: "s9-manim",
          layout: "manim",
          startMs: 0,
          durationMs: 3000,
          content: {
            sceneName: "SpecFlow",
            sceneSource: [
              "from manim import *",
              "",
              "class SpecFlow(Scene):",
              "    def construct(self):",
              "        self.play(Write(Text('prompt → spec → MP4')))",
            ].join("\n"),
          },
        },
      ],
    },
  ],
});
